name: BlackBlaze2Sync
options:
  bundleIdPrefix: mx.smh.blackblaze2sync
targets:
  BlackBlaze2Sync:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: mx.smh.blackblaze2sync.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ENABLE_APP_SANDBOX: NO
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.0"
